# Generated by Django 2.1.3 on 2018-12-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='deleted time'),
        ),
        migrations.AlterField(
            model_name='userproperty',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='deleted time'),
        ),
    ]
