# Generated by Django 2.2.3 on 2019-11-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cellphone',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='Cellphone'),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='电子邮件'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='value',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='指明用户是否被认为是活跃的。以反选代替删除帐号。', verbose_name='有效'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='指明用户是否可以登录到这个管理站点。', verbose_name='人员状态'),
        ),
    ]
