# Generated by Django 2.1.3 on 2018-11-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cellphone',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Cellphone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, db_index=True, default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='qq_openid',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='QQ OpenID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wechat_openid',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Wechat OpenID'),
        ),
        migrations.AlterField(
            model_name='userproperty',
            name='value',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Value'),
        ),
    ]
