# Generated by Django 2.1.3 on 2019-02-11 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190211_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLoginToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted time')),
                ('is_deleted', models.BooleanField(default=False)),
                ('qq', models.CharField(max_length=255, unique=True, verbose_name='QQ Token')),
                ('wechat', models.CharField(max_length=255, unique=True, verbose_name='Wechat Token')),
                ('facebook', models.CharField(max_length=255, unique=True, verbose_name='Facebook Token')),
                ('tiwtter', models.CharField(max_length=255, unique=True, verbose_name='Twitter Token')),
                ('google', models.CharField(max_length=255, unique=True, verbose_name='Google Token')),
            ],
            options={
                'verbose_name': 'Social Login Token',
                'verbose_name_plural': 'Social Login Token',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='qq_openid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='wechat_openid',
        ),
        migrations.AddField(
            model_name='sociallogintoken',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_login_token', related_query_name='social_login_token', to=settings.AUTH_USER_MODEL),
        ),
    ]
