# Generated by Django 2.1.3 on 2019-02-26 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20190220_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='OauthLoginProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted time')),
                ('is_deleted', models.BooleanField(default=False)),
                ('provider', models.CharField(db_index=True, max_length=255, verbose_name='Provider Name')),
                ('token', models.CharField(db_index=True, max_length=255, verbose_name='Provider Token')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_tokens', related_query_name='oauth_token', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'Oauth Login Provider',
                'verbose_name_plural': 'Oauth Login Providers',
            },
        ),
        migrations.RemoveField(
            model_name='sociallogintoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='SocialLoginToken',
        ),
    ]
