# Generated by Django 2.1.3 on 2019-02-26 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20190226_1022'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='oauthloginprovider',
            unique_together={('provider', 'token', 'user')},
        ),
        migrations.AddIndex(
            model_name='oauthloginprovider',
            index=models.Index(fields=['user', 'provider'], name='account_oau_user_id_b82b6c_idx'),
        ),
    ]
